# Generated by Django 3.1.3 on 2021-07-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210723_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ManyToManyField(to='onlinecourse.Question'),
        ),
    ]
